YouPost/YouPost/YouPost/Controllers/FeedController.cs
using Microsoft.AspNetCore.Mvc;
using YouPost.Data;
using YouPost.Models.ViewModels;
using YouPost.Repositories;

namespace YouPost.Controllers
{
    public class FeedController : Controller
    {
        private readonly UserRepository _repository;

        public FeedController(ApplicationDbContext context)
        {
            _repository = new UserRepository(context);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string username)
        {
            if (username != null)
            {
                var user = _repository.SearchByUsername(username);
                if(user != null)
                {
                    SearchUserModel model = new SearchUserModel();
                    model.ToModel(user);

                    return View(model);
                }
            }

            return View();
        }

    }
}

YouPost/YouPost/YouPost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YouPost</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style_menu.css" asp-append-version="true" />
     <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YouPost.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       <div class="sidenav">
            
            <br />
            <a class="nav-link border-top border-white " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Register">Registration</a>
            <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a>
            <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Login">Login</a>
            <a class="nav-link " asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
            <a class="nav-link " asp-area="" asp-controller="Feed" asp-action="Index">Лента</a>
        </div>
    </header>



    <div class="main">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>